// AUTO-GENERATED by `env-manager ts` - do not edit
import { z } from 'zod';

const env = z
	.object({
		API_PORT: z.coerce.number().int(),
		CLIENT_PORT: z.coerce.number().int(),
		VITE_API_URL: z.string(),
		GROQ_API_KEY: z.string(),
		GOOGLE_GENERATIVE_AI_API_KEY: z.string(),
	})
	.parse(process.env);

export default env;
